In [2]:
import numpy as np
 
def mat_encode(phrase):
    alphas = ' abcdefghijklmnopqrstuvwxyz'
    num_list = []
 
    # A is your encoding matrix for this. All input text is converted into numbers, split into mini- arrays which are then multiplied with your encoder.
    A = np.array([[5,3,1],
                  [-4,-5,-1],
                  [2,2,1]])     
    
    for i in phrase:
        num_list.append(alphas.index(i.lower()))
    
    mini_arrays = [np.array(num_list[j:j + 3]) for j in range(0, len(num_list), 3)] 
    
    encrypted_arrays = []
    for k in mini_arrays:
        encrypted_arrays.append(np.matmul(k, A))
        
    final = ''
    for l in encrypted_arrays:
        for m in l:
            final += str(m)
            final += ', '
            
    return final, mini_arrays


mat_encode("please send money ")    # Test call to this method

('42, -2, 9, -61, -82, -13, -66, -85, -14, 54, 22, 10, 33, -8, 12, -75, -110, -20, ',
 [array([16, 12,  5]),
  array([ 1, 19,  5]),
  array([ 0, 19,  5]),
  array([14,  4,  0]),
  array([13, 15, 14]),
  array([ 5, 25,  0])])

In [4]:
def mat_decode(encoded):
    #takes encoded as a list of integers
    n = 3
    alphas = []
    alphas.extend(' abcdefghijklmnopqrstuvwxyz')
    
    A_uninv = np.array([[2,1,2],
                        [1,1,2],
                        [2,2,5]])
    A = np.linalg.inv(A_uninv)
    
    mini_arrays = [np.array(encoded[j:j + n]) for j in range(0, len(encoded), n)] 
    
    decoded = []
    for i in mini_arrays:
        decoded.append(np.matmul(i,A))
    
    f = ''
    
    final = ''
    for l in decoded:
        for m in l:
            final += alphas[int(round(m,0))]
        
    return final

mat_decode([int(m) for m in "61   53   128   12   7   15   43   43   104   51   46   112   33   33   71   31   26   57   32   18   36  ".split()])

'have a great weekend '